name: flutter_lyra
description: Flutter Lyra
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_lyra_android
      ios:
        default_package: flutter_lyra_ios

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_lyra_android:
    path: ^0.1.0+1
  flutter_lyra_ios:
    path: ^0.1.0+1
  flutter_lyra_platform_interface:
    path: ^0.1.0+1

dev_dependencies:
  analyzer: ^4.7.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
