name: flutter_payzen_ios
description: iOS implementation of the flutter_payzen plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: flutter_payzen
    platforms:
      ios:
        pluginClass: FlutterPayzenPlugin
        dartPluginClass: FlutterPayzenIOS

dependencies:
  flutter:
    sdk: flutter
  flutter_payzen_platform_interface:
    path: ../flutter_payzen_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^3.0.1
