name: flutter_payzen
description: Flutter Payzen
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_payzen_android
      ios:
        default_package: flutter_payzen_ios

dependencies:
  flutter:
    sdk: flutter
  flutter_payzen_android:
    path: ../flutter_payzen_android
  flutter_payzen_ios:
    path: ../flutter_payzen_ios
  flutter_payzen_platform_interface:
    path: ../flutter_payzen_platform_interface

dev_dependencies:
  analyzer: ^4.7.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  plugin_platform_interface: ^2.0.0
