name: flutter_payzen_platform_interface
description: A common platform interface for the flutter_payzen plugin.
version: 0.1.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  analyzer: ^4.7.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  pigeon: ^4.0.0
