name: flutter_lyra_example
description: Demonstrates how to use the flutter_lyra plugin.
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_lyra:
    # When depending on this package from a real application you should use:
    #   flutter_lyra: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  analyzer: ^4.7.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
